import type { APIRoute } from 'astro';
import { SITE_URL } from '../lib/seo';

export const GET: APIRoute = ({ site }) => {
  const sitemapURL = new URL('sitemap.xml', site ?? SITE_URL);

  return new Response(
    [
      'User-agent: *',
      'Allow: /',
      'Disallow: /api/',
      'Disallow: /demos/',
      'Disallow: /page/',
      'Disallow: */page/*',
      'Disallow: /blog/page/',
      '',
      '# AI & Generative Engine Crawlers — Explicitly allowed for GEO and Search',
      'User-agent: Googlebot',
      'Allow: /',
      'Disallow: /api/',
      'Disallow: /demos/',
      'Disallow: /page/',
      'Disallow: */page/*',
      '',
      'User-agent: Bingbot',
      'Allow: /',
      'Disallow: /api/',
      'Disallow: /demos/',
      'Disallow: /page/',
      'Disallow: */page/*',
      '',
      'User-agent: OAI-SearchBot',
      'Allow: /',
      'Disallow: /api/',
      'Disallow: /demos/',
      'Disallow: /page/',
      'Disallow: */page/*',
      '',
      'User-agent: ChatGPT-User',
      'Allow: /',
      'Disallow: /api/',
      'Disallow: /demos/',
      'Disallow: /page/',
      'Disallow: */page/*',
      '',
      'User-agent: ClaudeBot',
      'Allow: /',
      'Disallow: /api/',
      'Disallow: /demos/',
      'Disallow: /page/',
      'Disallow: */page/*',
      '',
      'User-agent: PerplexityBot',
      'Allow: /',
      'Disallow: /api/',
      'Disallow: /demos/',
      'Disallow: /page/',
      'Disallow: */page/*',
      '',
      'User-agent: Google-Extended',
      'Allow: /',
      'Disallow: /api/',
      'Disallow: /demos/',
      'Disallow: /page/',
      'Disallow: */page/*',
      '',
      `Sitemap: ${sitemapURL.href}`,
      '',
      '# GEO Context: https://tap-ia.tech/llms.txt',
      '# GEO Full Context: https://tap-ia.tech/llms-full.txt',
      '',
    ].join('\n'),
    {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
      },
    }
  );
};
